version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount Docker socket
    depends_on:
      - gitea
    environment:
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"
    user: root  # Set Jenkins user to root to allow Docker CLI access
    privileged: true  # Run container in privileged mode for Docker support
    command: bash -c "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && usermod -aG docker jenkins && chown jenkins:jenkins /var/run/docker.sock && /sbin/tini -- /usr/local/bin/jenkins.sh"

  gitea:
    image: gitea/gitea:latest
    ports:
      - "3000:3000"
    volumes:
      - "gitea_data:/data"
    environment:
      - "DB_TYPE=mysql"
      - "DB_HOST=mysql"
      - "DB_NAME=gitea"
      - "DB_USER=root"
      - "DB_PASS=password"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=gitea"

volumes:
  jenkins_home:
  gitea_data:
  mysql_data:
